### POST Method FOR REGISTRATION
POST  http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
   "name": "Test",
    "email": "test@test.com",
    "password": "password",
    "phone":"123456789",
    "address": "Mumbai India"
}


### Login User
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin@123"
}

### Testing token base authentication 
GET http://localhost:5000/api/v1/auth/test
Content-Type:application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDEzNzQyMmZkYTFjYTJjNTBkZDVlZjUiLCJpYXQiOjE2NzkwNTY0ODksImV4cCI6MTY3OTY2MTI4OX0.tCeXf8EM_NzvWBljWrq6nZt7g7YEuYpG9zbWzpw2MYo


###

GET http://localhost:5000/api/v1/auth/userAuth

###
// Create Category
POST http://localhost:5000/api/v1/category/create-category
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDFhZmRjNThkZGFlN2Y5M2ZhYjdjMzkiLCJpYXQiOjE2Nzk5MjQ1MzQsImV4cCI6MTY4MDUyOTMzNH0.39fwnxDESfV9MX1KzxUs2z-7wuQuIY9DzWgUsQf-8VQ

{
    "name":"womens watches"
}

###
// Update the category
PUT  http://localhost:5000/api/v1/category/update-category/64219c9db7920059b80701ed
Content-Type:application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDFhZmRjNThkZGFlN2Y5M2ZhYjdjMzkiLCJpYXQiOjE2Nzk5MjQ1MzQsImV4cCI6MTY4MDUyOTMzNH0.39fwnxDESfV9MX1KzxUs2z-7wuQuIY9DzWgUsQf-8VQ

{
    "name":"Electronic"
}

###
// getAll categories
GET  http://localhost:5000/api/v1/category/getCategory

###
// get Single Category
GET  http://localhost:5000/api/v1/category/getSingleCategory/womens-watches

###
// delete single category
DELETE   http://localhost:5000/api/v1/category/deleteCategory/6421a55de4e06cada05fa4ae
Content-Type: :application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDFhZmRjNThkZGFlN2Y5M2ZhYjdjMzkiLCJpYXQiOjE2Nzk5MjQ1MzQsImV4cCI6MTY4MDUyOTMzNH0.39fwnxDESfV9MX1KzxUs2z-7wuQuIY9DzWgUsQf-8VQ

###
// Create A New Products
POST  http://localhost:5000/api/v1/products/create-product
Content-Type: :application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDFhZmRjNThkZGFlN2Y5M2ZhYjdjMzkiLCJpYXQiOjE2Nzk5MjQ1MzQsImV4cCI6MTY4MDUyOTMzNH0.39fwnxDESfV9MX1KzxUs2z-7wuQuIY9DzWgUsQf-8VQ


###
// get all products
GET http://localhost:5000/api/v1/products/getProducts


###
// get photo using id
GET  http://localhost:5000/api/v1/products/product-photo/642b9f4035e368b88c00f42d


###
GET http://localhost:5000/api/v1/users/User/64137422fda1ca2c50dd5ef5
Content-Type: application/json

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDFhZmRjNThkZGFlN2Y5M2ZhYjdjMzkiLCJpYXQiOjE2ODA1MzM1MDQsImV4cCI6MTY4MTEzODMwNH0.wTB0xS5fwXSdwE7r31cRhvTajMwLw9HUefGzDyLB9q8